/**
 * @file help_text.h
 * @brief Help text constant for F256 Switcharoo
 */


const char *help_text =
"\n"
"\n"
"            ^4   _____         _ __       __                        \n"
"            ^4  / ___/      __(_) /______/ /_  ^5___  _________  ____ \n"
"            ^4  \\__ \\ | /| / / / __/ ___/ __ \\^5/ _ \\/ ___/ __ \\/ __ \\\n"
"            ^4 ___/ / |/ |/ / / /_/ /__/ / / ^5/  __/ /  / /_/ / /_/ /\n"
"            ^4/____/|__/|__/_/\\__/\\___/_/ /_/^5\\___/_/   \\____/\\____/ \n"
"\n"
"\n"
"    ^6HOW TO PLAY:\n"
"    ^11. Objective is to create a connected path between the 2nd and 7th rows.\n"
"    2. A piece moves one cell in any direction.\n"
"    3. A piece may exchange positions with an opponent's adjacent piece. Both\n"
"       pieces are marked with a crown to indicate they have been swapped.\n"
"    4. Swapped pieces cannot be the target of a swapping move.\n"
"    5. When a piece is moved to an empty cell, swapped pieces are cleared\n"
"       based on the current selected swapping rule.\n"
"\n"
"    ^6SWAP RULES:\n"
"    ^1Any - All:  Any move to empty cell clears all swapped pieces.\n"
"    Any - Own:  Any move to empty cell clears the mover's pieces.\n"
"    Swap - All: Swapped piece move to empty cell clears all.\n"
"    Swap - Own: Swapped piece move to empty cell clears the mover's pieces.\n"
"\n"
"    ^6PUZZLES:\n"
"    ^1Puzzles are forced Wins in 2, 3 or 4 moves. The objective is \n"
"    to find the winning line in the specified number of moves.\n"
"\n"
"    ^6FREE PLAY:\n"
"    ^1There are 4 starting boards.  Boards with pieces in the center have\n"
"    more immediate tactical play.\n"
"\n"
"    ^6ACTIONS AND HOTKEYS:\n"
"    ^1Select piece with mouse and click a legal target cell to move.\n"
"    You can also use cursor keys and space or enter to select pieces\n"
"    and target cells.\n"
"\n"
"    [^6M^1] Mode:         Toggle between Puzzle and Free Play mode.\n"
"    [^6R^1] Reset:        Reset the current board back to the starting position.\n"
"    [^6P^1] Previous:     Previous puzzle or starting board.\n"
"    [^6N^1] Next:         Next puzzle or starting board.\n"
"    [^6S^1] Swap-Rule:    Select a swap rule for Puzzle or Free Play.\n"
"    [^6D^1] Difficulty:   Select an engine difficulty.\n"
"    [^6H^1] Hint:         Provide a hint for the Puzzle or Free Play position.\n"
"    [^6A^1] Achievements: View achievements and statistics.\n"
"    [^6B^1] Back:         Back to prior position in Free Play mode.\n"
"    [^6F^1] Forward:      Forward to next position in Free Play mode.\n"
"    [^6X^1] Exit:         Exit the game.\n"
"\n"
"    ^6TIPS:\n"
"    ^11. Use swaps to form blockades\n"
"    2. Use adjacent pieces on a row for more than one attack\n"
"    3. Breakup opponent's connection progress by swapping pieces.\n"
"    4. Move to empty cells for better positioning or to break blockades.\n"
"\n"
"\n"
"                            Press [^6SPACE^1] to exit.\n";

